name: Update HTML File

on:
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Get commit message and changed files
      id: get-info
      run: |
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV
        echo "CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4

    - name: Update HTML file
      run: |
        python generate_log.py

    - name: Commit changes
      if: contains(github.event.head_commit.message, 'Update')
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'Your Name'
        author_email: 'your.email@example.com'
        message: 'Update HTML file with new <li> tag'
        add: 'index.html'
        token: ${{ secrets.PAT_TOKEN }}
