name: Update HTML File

on:
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Get commit message and changed files
      id: get-info
      run: |
        # 최신 커밋 해시 가져오기
        COMMIT_HASH=$(git rev-parse HEAD)
        
        # 최신 커밋 메시지 가져오기
        COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' ${COMMIT_HASH})

        # 변경된 파일 목록 가져오기
        CHANGED_FILES=$(git diff --name-only ${COMMIT_HASH}^ ${COMMIT_HASH})

        # Python 스크립트 실행
        python generate_log.py "$COMMIT_MESSAGE" "$CHANGED_FILES"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4

    - name: Commit changes
      if: contains(github.event.head_commit.message, 'Update')
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'Your Name'
        author_email: 'your.email@example.com'
        message: 'Update HTML file with new <li> tag'
        add: 'index.html'
        token: ${{ secrets.PAT_TOKEN }}
