name: Update HTML File

on:
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}  # PAT을 사용하여 체크아웃

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4

    - name: Update HTML file
      run: |
        python generate_log.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'Your Name'
        author_email: 'your.email@example.com'
        message: 'Add new <li> elements to index.html'
        add: 'index.html'
        token: ${{ secrets.PAT_TOKEN }}  # PAT을 사용하여 커밋
